const productos = [
  { id: 1, foto: 'https://res.cloudinary.com/ijac-it-solutions/image/upload/v1639592180/img/intel_i9_11th_rkievv.jpg', categoria: 'procesadores', name: "Micro i9", price: 80000, stock: 20, descripcion: "ESPECIFICACIONES TECNICAS - Marca: Intel- Modelo: BX8070811900K- Tipos de memoria RAM soportadas DDR4- Tamaño máximo de memoria RAM soportada 128 GB- Caché 16 MB- Zócalos compatibles FCLGA1200- Arquitectura x64- Aplicación Computadoras de escritorio- Procesador gráfico Intel UHD Graphics 750- Cantidad de núcleos de CPU 8- Es gamer Sí- Está desbloqueado Sí- Frecuencia mínima de reloj 3 GHz- Frecuencia máxima de reloj 5 GHz" },
  { id: 2, foto: 'https://res.cloudinary.com/ijac-it-solutions/image/upload/v1639591756/img/crucial_vegeance_iywazh.jpg', categoria: 'memorias', name: "Crucial 32GB DDR4 3000Mhz", price: 20000, stock: 20, descripcion: "Con diseños únicos y modernos, Corsair es una de las marcas más elegidas por los usuarios al momento de comprar una memoria ram. Cargar programas más rápido, aumentar la capacidad de responder y ejecutar aplicaciones de uso intensivo son algunas de las características y ventajas que tendrás al momento de adquirir esta memoria." },
  { id: 3, foto: 'https://res.cloudinary.com/ijac-it-solutions/image/upload/v1639592787/img/ssd_1tb_wd_xzsk8s.jpg', categoria: 'discos', name: "Western Digital M2 1TB", price: 15000, stock: 15, descripcion: "Western Digital es una marca de renombre mundial en almacenamiento de datos con la cual podés crear, experimentar y guardar contenidos a través de una amplia gama de dispositivos. La alta seguridad y rendimiento que brindan sus unidades la convierten en una de las empresas más elegidas del mercado. El WD Blue SN550 WDS100T2B0C está adaptado para que puedas acceder de forma rápida a tus documentos digitales gracias a su tecnología en estado sólido." },
  { id: 4, foto: 'https://res.cloudinary.com/ijac-it-solutions/image/upload/v1639593041/img/asus_tuf_wifi_gseius.png', categoria: 'motherboards', name: "Asus TUF Z490 Wifi", price: 25000, stock: 20, descripcion: "ASUS TUF Gaming Z490-Plus (WiFi 6), LGA 1200 (Intel 10th Gen) ATX Gaming Motherboard (Dual M.2, 122 Power Stages, USB 3.2 Front Panel Type-C, Intel WiFi 6 and 1Gb LAN, Aura Sync)" },
  { id: 5, foto: 'https://res.cloudinary.com/ijac-it-solutions/image/upload/v1639593623/img/placa_de_video_1050ti2_osvr72.jpg', categoria: 'placas', name: "Gigabyte Geforce 1050Ti", price: 60000, stock: 20, descripcion: "Especificaciones técnicas:Graphics Processing GeForce® GTX 1050 TiCore Clock- Boost: 1430 MHz / Base: 1316 MHz in OC mode- Boost: 1392 MHz / Base: 1290 MHz in Gaming modeCUDA® Cores 768Memory Clock 7008 MHzMemory Size 4 GBMemory Type GDDR5Memory Bus 128 bitCard Bus PCI-E 3.0 x 16Digital max resolution 7680x4320Multi-view 3Card size H=30 L=172 W=113 mmPCB Form ATXDirectX 12OpenGL 4.5Power Connectors N/AOutput- Dual-link DVI-D *1- HDMI-2.0b*1 (Max Resolution: 4096x2160 @60 Hz)- Display Port-1.4 *1 (Max Resolution: 7680x4320 @60 Hz)" },
  { id: 6, foto: 'https://res.cloudinary.com/ijac-it-solutions/image/upload/v1639593730/img/western_digital_1tb_dmyt3p.jpg', categoria: 'discos', name: "Disco Rígido Western Digital Blue 1TB", price: 5200, stock: 20, descripcion: "Western Digital es una marca de renombre mundial en almacenamiento de datos con la cual podés crear, experimentar y guardar contenidos a través de una amplia gama de dispositivos. La alta seguridad y rendimiento que brindan sus unidades la convierten en una de las empresas más elegidas del mercado.El WD Blue WD5000AAKX se caracteriza por su eficiencia y buen funcionamiento, que sumado a su reducido consumo energético lo vuelven un disco indispensable para funciones estándar." },
  { id: 7, foto: 'https://res.cloudinary.com/ijac-it-solutions/image/upload/v1639593925/img/z20_gabo_jomzfo.jpg', categoria: 'gabinetes', name: "Gabinete Sentey Z20", price: 30000 , stock: 20, descripcion: "Especificaciones• Marca: Sentey• Modelo: Z20 4295-SF2• Tipo: Mid Tower• Color: Negro• Material: SPCC• Motherboard Compatibles: ATX, M-ATX• Posición PSU: Inferior trasera• Tamaño máximo VGA: 349mm• Tamaño máximo CPU cooler: 166mm• Soporte Watercooling: si• Bahias int 3.5”:2• Bahias int 2.5”:2• Expansion Slot PCI:7• USB 3.0: 2• USB 2.0: 1• Audio Frontal: HD Audio• Cooler Frontal: 3x120mm LEDs RGB• Cooler trasero: 1x120mmLEDs RGB• Alto: 489mm• Ancho: 206 mm• Largo: 436mm"},
  { id: 8, foto: 'https://res.cloudinary.com/ijac-it-solutions/image/upload/v1639594087/img/fuente_thermlatake_ejuzhr.jpg', categoria: 'fuentes', name: "Fuente thermaltake Smart 600W", price: 12000, stock: 20, descripcion: "•Especificaciones Tecnicas Marca: Thermaltake Modelo: SP-600AH2NKWP/N: PS-SPD-0600NPCW-W Short P/N: SPD-0600P Tipo: Intel ATX 12V 2.3 Potencia: 600W Color: Negro Dimensiones: 86mm x 150mm x 140mm PFC (Power Factor Correction): Active PFC Power Good Signal: 100-500 msec Hold Up Time: 16msec (minimum) within 60% load Eficiencia: 82-86% efficiency @ 20-100% load MTBF: 100,000 hrs minimum Corriente de entrada: 10A max Frecuencia de entrada: 50 Hz - 60 Hz Voltaje de entrada: 100Vac – 240Vac Temperatura de operación: 5 a 40 grados Humedad de operación: 20% to 85%,non-condensing"}
]



export const getFetch = new Promise((resolve) =>{
    // acciones que pueden ser asincrónicas o no setTime
    setTimeout(()=>{
        resolve(productos)
    }, 3000)
    
}) // Instanciar el objeto